name: RestSharp tests
on:
  push:
    branches: ['main']
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        run: dotnet test -l "html;LogFileName=index.html"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: RunReports
          path: RestSharpTests/TestResults

      - uses: JamesIves/github-pages-deploy-action@v4
        if: always()
        with:
          branch: gh-pages
          folder: RestSharpTests/TestResults
